import ProjectDescription
import ProjectDescriptionHelpers

let CIScheme = Scheme(
  name: "CI",
  testAction:
      .testPlans(
        [
          "TestPlans/CI.xctestplan",
        ],
        attachDebugger: false
      )
)

let iosCIScheme = Scheme(
  name: "CI-iOS",
  testAction:
  .testPlans(
    [
      "TestPlans/CI-iOS.xctestplan",
    ],
    attachDebugger: false
  )
)

let macCIScheme = Scheme(
  name: "CI-macOS",
  testAction:
  .testPlans(
    [
      "TestPlans/CI-macOS.xctestplan",
    ],
    attachDebugger: false
  )
)

let iOS = Scheme(
  name: "iOS",
  buildAction: .buildAction(
    targets: [
      .foundation("Core"),
      .foundation("UI"),
      .app("iOS"),
    ]
  ),
  runAction: .runAction(executable: .app("iOS"))
)

let workspace = Workspace(
  name: ProjectConfiguration.appName,
  projects: [
    "Apps/iOS",
  ],
  schemes: [
    macCIScheme,
    iosCIScheme,
    CIScheme,
    iOS,
  ],
  fileHeaderTemplate: "",
  additionalFiles: [
    .folderReference(path: .relativeToRoot("TestPlans")),
  ], generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .disabled,
    lastXcodeUpgradeCheck: .init(14, 3, 0),
    renderMarkdownReadme: true
  )
)
